import {
  MobileHome,
  Tenant,
  Reservation,
  OperationalTask,
  InventoryItem,
  Expense,
  ReservationStatus,
  TaskType,
  TaskStatus,
  DepositStatus,
  Platform,
  ExpenseCategory,
} from "@/types";

// Mock Mobile Homes
export const mockMobileHomes: MobileHome[] = [
  {
    id: "mh-1",
    name: "Mobil-Home Premium Vue Mer",
    description: "Magnifique mobil-home avec vue panoramique sur la mer",
    location: "Camping Les Sables d'Or, Vendée",
    capacity: 6,
    bedrooms: 3,
    bathrooms: 1,
    amenities: ["Climatisation", "Terrasse", "WiFi", "TV", "Barbecue"],
    photos: ["/placeholder-mobilhome.jpg"],
    basePrice: 120,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-20"),
  },
  {
    id: "mh-2",
    name: "Mobil-Home Confort Familial",
    description: "Parfait pour les familles, proche des animations",
    location: "Camping Les Sables d'Or, Vendée",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["WiFi", "TV", "Terrasse"],
    photos: ["/placeholder-mobilhome.jpg"],
    basePrice: 85,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-20"),
  },
];

// Mock Tenants
export const mockTenants: Tenant[] = [
  {
    id: "t-1",
    firstName: "Marie",
    lastName: "Dupont",
    email: "marie.dupont@email.fr",
    phone: "+33 6 12 34 56 78",
    createdAt: new Date("2024-06-15"),
  },
  {
    id: "t-2",
    firstName: "Jean",
    lastName: "Martin",
    email: "jean.martin@email.fr",
    phone: "+33 6 98 76 54 32",
    createdAt: new Date("2024-07-10"),
  },
  {
    id: "t-3",
    firstName: "Sophie",
    lastName: "Bernard",
    email: "sophie.bernard@email.fr",
    phone: "+33 6 11 22 33 44",
    createdAt: new Date("2024-08-05"),
  },
];

// Mock Reservations
export const mockReservations: Reservation[] = [
  {
    id: "res-1",
    mobileHomeId: "mh-1",
    tenantId: "t-1",
    checkInDate: new Date("2025-07-15"),
    checkOutDate: new Date("2025-07-22"),
    numberOfGuests: 5,
    totalPrice: 840,
    platformFee: 84,
    netRevenue: 756,
    status: ReservationStatus.CONFIRMED,
    platform: Platform.AIRBNB,
    depositAmount: 500,
    depositStatus: DepositStatus.RECEIVED,
    depositReceivedDate: new Date("2025-06-15"),
    notes: "",
    confirmationSent: true,
    arrivalInstructionsSent: false,
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-06-15"),
  },
  {
    id: "res-2",
    mobileHomeId: "mh-1",
    tenantId: "t-2",
    checkInDate: new Date("2025-08-01"),
    checkOutDate: new Date("2025-08-08"),
    numberOfGuests: 4,
    totalPrice: 840,
    platformFee: 126,
    netRevenue: 714,
    status: ReservationStatus.CONFIRMED,
    platform: Platform.BOOKING,
    depositAmount: 500,
    depositStatus: DepositStatus.AWAITING,
    notes: "",
    confirmationSent: true,
    arrivalInstructionsSent: false,
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2025-06-10"),
  },
  {
    id: "res-3",
    mobileHomeId: "mh-2",
    tenantId: "t-3",
    checkInDate: new Date("2025-11-01"),
    checkOutDate: new Date("2025-11-05"),
    numberOfGuests: 3,
    totalPrice: 340,
    platformFee: 0,
    netRevenue: 340,
    status: ReservationStatus.PENDING,
    platform: Platform.DIRECT,
    depositAmount: 300,
    depositStatus: DepositStatus.AWAITING,
    notes: "Réservation directe via le site web",
    confirmationSent: false,
    arrivalInstructionsSent: false,
    createdAt: new Date("2025-10-20"),
    updatedAt: new Date("2025-10-20"),
  },
];

// Mock Operational Tasks
export const mockTasks: OperationalTask[] = [
  {
    id: "task-1",
    mobileHomeId: "mh-1",
    reservationId: "res-1",
    type: TaskType.CLEANING,
    title: "Ménage avant arrivée - Dupont",
    description: "Ménage complet avant l'arrivée des locataires",
    assignedTo: "Société CleanPro",
    dueDate: new Date("2025-07-14"),
    status: TaskStatus.PENDING,
    createdAt: new Date("2025-06-15"),
    updatedAt: new Date("2025-06-15"),
  },
  {
    id: "task-2",
    mobileHomeId: "mh-1",
    reservationId: "res-1",
    type: TaskType.INVENTORY_CHECK,
    title: "État des lieux d'entrée - Dupont",
    description: "Effectuer l'état des lieux à l'arrivée",
    assignedTo: "Gardien du camping",
    dueDate: new Date("2025-07-15"),
    status: TaskStatus.PENDING,
    createdAt: new Date("2025-06-15"),
    updatedAt: new Date("2025-06-15"),
  },
  {
    id: "task-3",
    mobileHomeId: "mh-1",
    type: TaskType.MAINTENANCE,
    title: "Vérification climatisation",
    description: "Contrôle et entretien annuel de la climatisation",
    assignedTo: "Technicien Clim Service",
    dueDate: new Date("2025-06-30"),
    status: TaskStatus.COMPLETED,
    completedAt: new Date("2025-06-28"),
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-28"),
  },
];

// Mock Inventory Items
export const mockInventoryItems: InventoryItem[] = [
  {
    id: "inv-1",
    mobileHomeId: "mh-1",
    name: "Télévision LED 32 pouces",
    category: "Électronique",
    quantity: 1,
    condition: "Bon état",
    lastChecked: new Date("2025-06-01"),
  },
  {
    id: "inv-2",
    mobileHomeId: "mh-1",
    name: "Draps housse (160x200)",
    category: "Linge de maison",
    quantity: 3,
    condition: "Bon état",
    lastChecked: new Date("2025-06-01"),
  },
  {
    id: "inv-3",
    mobileHomeId: "mh-1",
    name: "Chaises de jardin",
    category: "Mobilier extérieur",
    quantity: 6,
    condition: "Bon état",
    lastChecked: new Date("2025-06-01"),
  },
  {
    id: "inv-4",
    mobileHomeId: "mh-1",
    name: "Vaisselle complète (assiettes)",
    category: "Cuisine",
    quantity: 18,
    condition: "Bon état",
    lastChecked: new Date("2025-06-01"),
  },
];

// Mock Expenses
export const mockExpenses: Expense[] = [
  {
    id: "exp-1",
    mobileHomeId: "mh-1",
    category: ExpenseCategory.PARCEL_RENT,
    description: "Loyer parcelle - Année 2025",
    amount: 3500,
    date: new Date("2025-01-15"),
    taxDeductible: true,
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "exp-2",
    mobileHomeId: "mh-1",
    category: ExpenseCategory.INSURANCE,
    description: "Assurance habitation LMNP",
    amount: 450,
    date: new Date("2025-02-01"),
    invoiceUrl: "/invoices/insurance-2025.pdf",
    taxDeductible: true,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "exp-3",
    mobileHomeId: "mh-1",
    category: ExpenseCategory.CLEANING,
    description: "Ménage saison été (15 passages)",
    amount: 675,
    date: new Date("2025-09-30"),
    taxDeductible: true,
    createdAt: new Date("2025-09-30"),
  },
  {
    id: "exp-4",
    mobileHomeId: "mh-1",
    category: ExpenseCategory.MAINTENANCE,
    description: "Entretien climatisation",
    amount: 120,
    date: new Date("2025-06-28"),
    invoiceUrl: "/invoices/clim-maintenance.pdf",
    taxDeductible: true,
    createdAt: new Date("2025-06-28"),
  },
];
